.TH "NETFLIX\-SEARCH" "" "April 2015" "" ""
.SH "NAME"
\fBnetflix-search\fR
.P
Simple shell tool to search for movies on the canistream\.it api\.
.SH Installation
.P
Download node at nodejs\.org \fIhttp://nodejs\.org\fR and install it, if you haven't already\. 
.P
.RS 2
.nf
 $ npm install \-g
.fi
.RE
.SH Usage
.P
To call netflix\-search  just type in the command
.P
.RS 2
.nf
 $ netflix search
.fi
.RE
.P
Now type in the movie you want to watch\. You should be presented with a list of options, use the up and down arrow keys to navigate\. Using the right arrow key you can then select any link you would like to view and then press enter\. This will open the link in your default browser\.
.SH Example
.P
alt tag \fIhttps://raw\.githubusercontent\.com/farrelke/netflix\-search/master/screencast\.gif\fR
